export * from './requestWinners';
export * from './storeWinner';
export * from './battleStart';

export const Types = { 
	REQUEST_WINNERS : 'REQUEST_WINNERS',
	SUCCESS_REQUEST_WINNERS : 'SUCCESS_REQUEST_WINNERS',
	ERROR_REQUEST_WINNERS : 'ERROR_REQUEST_WINNERS',
	
	BATTLE_START : 'BATTLE_START',
	BATTLE_START_SUCCESS : 'BATTLE_START_SUCCESS', 
	BATTLE_START_ERROR : 'BATTLE_START_ERROR',
	STORE_WINNER : 'STORE_WINNER'
};
