export * from './requestWinners';
export * from './battleActions';

export const Types = { 
	REQUEST_WINNERS : 'Winners/REQUEST_WINNERS',
	REQUEST_WINNERS_SUCCESS : 'Winners/REQUEST_WINNERS_SUCCESS',
	REQUEST_WINNERS_ERROR : 'Winners/REQUEST_WINNERS_ERROR',
	
	BATTLE_START : 'Battle/BATTLE_START',
	BATTLE_START_SUCCESS : 'Battle/BATTLE_START_SUCCESS', 
	BATTLE_START_ERROR : 'Battle/BATTLE_START_ERROR',
	ANSWER_QUESTION : 'Battle/ANSWER_QUESTION',
	STORE_WINNER : 'Battle/STORE_WINNER',
	STORE_WINNER_SUCCESS : 'Battle/STORE_WINNER_SUCCESS',
	STORE_WINNER_ERROR : 'Battle/STORE_WINNER_ERROR',
	STORE_WINNER_NULL : 'Battle/STORE_WINNER_NULL'
};
