export const REQUEST_WINNERS = 'REQUEST_WINNERS';
export const SUCCESS_REQUEST_WINNERS = 'SUCCESS_REQUEST_WINNERS'
export const ERROR_REQUEST_WINNERS = 'ERROR_REQUEST_WINNERS';

export const requestWinners = () => ({
	type : REQUEST_WINNERS
});